# Generated by Django 4.1.5 on 2023-01-31 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('PointOfInterest', 'Landmarks')
    ]
