# Generated by Django 4.1.5 on 2023-02-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20230131_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
            ],
        ),
    ]
