# Generated by Django 4.1.5 on 2023-02-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_landdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landdb',
            old_name='adress',
            new_name='address',
        ),
    ]
