# Generated by Django 4.1.5 on 2023-02-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_rename_adress_landdb_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.JSONField()),
                ('duration', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
            ],
        ),
    ]
