# Generated by Django 4.1.5 on 2023-02-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='address',
            field=models.TextField(),
        ),
    ]
